<!-- This file contains styles, scripts and other information that goes in the 
head of each document that takes Milne Library styles and javascripts, Geneseo styles and icons, GIST4Web styles -->
<!DOCTYPE html lang="en">
<meta http-equiv="Cache-Control" content="no-cache, no-store, must-revalidate" />
<meta http-equiv="Pragma" content="no-cache" />
<meta http-equiv="Expires" content="0" />
<meta http-equiv="X-UA-Compatible" content="IE=EmulateIE7, IE=EmulateIE9, IE=EDGE" />
<meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0" />
<meta name="apple-mobile-web-app-capable" content="yes" />
<meta name="apple-mobile-web-app-status-bar-style" content="default" />
<link rel="apple-touch-icon" href="iphone-icon.png" />
      <meta charset="utf-8" />
<link rel="shortcut icon" href="https://www.geneseo.edu/sites/all/themes/geneseo_library/favicon.ico"" type="image/x-icon" />


  <!--INTRANET LIB CUSTOM STYLES & JQUERY LIBRARIES -->
<link type="text/css" href="https://eres.geneseo.edu/milne-styles-js/geneseo_all_milne_library.css" rel="stylesheet" media="all"  /> 
<link href="https://eres.geneseo.edu/milne-styles-js/jquery-ui-datepicker-milne.min.css" rel="stylesheet" />
<link href="https://eres.geneseo.edu/milne-styles-js/jquery-ui-1.10.3.custom-milne.min.css" rel="stylesheet" />
<script src="https://eres.geneseo.edu/milne-styles-js/js/jquery-ui-datepicker-milne.min.js"></script> 
<script type="text/javascript" src="https://eres.geneseo.edu/milne-styles-js/js/jquery.ui.timepicker.min.js"></script>
<script type="text/javascript" src="https://eres.geneseo.edu/milne-styles-js/js/jquery-ui-1.10.3.custom.min.js"></script>
<!-- link rel="stylesheet" type="text/css" href="https://illiad.geneseo.edu/styles/GIST4Web.css" media="all" -->
   <!--END INTRANET LIB CUSTOM STYLES & JQUERY LIBRARIES -->

	
<style>
@font-face {
    font-family: "Neutraface Text";
    src: url('fonts/NeutrafaceText-Book.eot');
    src: url("fonts/NeutrafaceText-Book.eot?#iefix") format("embedded-opentype"),
         url("fonts/NeutrafaceText-Book.woff2") format("woff2"),
         url("fonts/NeutrafaceText-Book.woff") format("woff");
    font-style: normal;
    font-weight: 400;
    font-stretch: normal;
}

@font-face {
    font-family: "Neutraface Headings";
    src: url('fonts/NeutrafaceText-Bold.eot');
    src: url("fonts/NeutrafaceText-Bold.eot?#iefix") format("embedded-opentype"),
         url("fonts/NeutrafaceText-Bold.woff2") format("woff2"),
         url("fonts/NeutrafaceText-Bold.woff") format("woff");
    font-style: normal;
    font-weight: 400;
    font-stretch: normal;
}

@font-face {
  font-family: 'Material Icons';
  font-style: normal;
  font-weight: 400;
  src: url(MaterialIcons-Regular.eot); /* For IE6-8 */
  src: local('../fonts/Material Icons'),
       local('fonts/MaterialIcons-Regular'),
       url(fonts/MaterialIcons-Regular.woff2) format('woff2'),
       url(fonts/MaterialIcons-Regular.woff) format('woff'),
       url(fonts/MaterialIcons-Regular.ttf) format('truetype');
}


.s-la-widget *, #s-la-widget-761
{ /*styles for the Frequently Asked Questions widget */
background:transparent !important;
background:none !important;
border:none !important;
padding-left: 5px !important;
}

.s-la-widget h1, .s-la-widget h3,  #s-la-widget-761 h1, #s-la-widget-761 h3
{
display: none !important;
visibiliy: hiddenn !important;
}

.s-la-widget .s-la-widget-header, #s-la-widget-761 .s-la-widget-header{
margin-bottom: 5px !important;
}


.s-la-widget .s-la-faq-listing-meta
{
display: none !important;
visibiliy: hiddenn !important;
}

body, div, p, td, tr {
font-family: "Open Sans",sans-serif;
font-weight:normal !important;
}

#s-la-widget-761 a{
font-family: "Open Sans",sans-serif;
font-weight:bold;
font-size:16px !important;
}
#s-la-widget-761 a:link, #s-la-widget-761 a:visited
{
 color: #345290;
}

#s-la-widget-761 a:hover
{
 color: #86C1EA;
}
h2{
font-size: 1.6em !important;
}

h3, h3 widget_title{
font-size: 1.4em !important;

}

span.statusNormal{
font-size: 1.3em !important;
color: #b85533;
}

table, td {background:none !important; background-color:none !important;
}

table, th,tr, td {
    border: 1px solid  #cccccc !important;
    border-collapse: collapse;
}
th,tr,td {
    padding: 5px 10px 5px 10px !important;
}

.row-header th{
background-color:#f1f8fc !important;
font-size: 1.2em !important;
color:#b87733 !important;
}

.row-headings th{
background-color:#ffffea !important;
font-size: 1.1em !important;}

tr {background-color: #eeeeee !important;}

tr:nth-child(even) {background: #f9f9f9 !important;}
tr:nth-child(odd) {background: #ffffff  !important;}


</style>	
	


<body>
    

<div><!---  main  --->
<div style="height: 20px;width: 100%; margin: 0px ! important;
background-color: #345290;"></div>
<div style="margin:0px 20px 20px 20px;">
    <div style="width: 100%;">   
        
<div style="float:left; margin-top:-20px;"><a href="https://www.geneseo.edu/library"><img src="https://eres.geneseo.edu/milne-logo/milne-library-logo.png" style="margin-top:0px; width:85%;"</a> </div>   	
		</div>
		
<div class="breadcrumb" style="margin-top:20px;"><a href="https://www.geneseo.edu/">SUNY Geneseo</a> &raquo; <a href="https://www.geneseo.edu/library">Milne Library</a> &raquo; <a href="https://illiad.geneseo.edu" style="color:#b85533 !important;">Information Delivery Services</a></div>
<div id="rightSideContent" >
<!--- BODY CONTENT RIGHT SIDE  BEGINS --->