<!-- This file contains styles, scripts and other information that goes in the 
head of each document that takes the drupal template -->
<!DOCTYPE html lang="en">
<meta http-equiv="X-UA-Compatible" content="IE=EmulateIE7, IE=EmulateIE9, IE=EDGE" />
      <meta charset="utf-8" />
<link rel="shortcut icon" href="https://www.geneseo.edu/sites/all/themes/geneseo_library/favicon.ico"" type="image/x-icon" />


  <!--INTRANET LIB CUSTOM STYLES & JQUERY LIBRARIES -->
	 <link type="text/css" href="https://eres.geneseo.edu/milne-styles-js/geneseo_all_milne_library.min.css" rel="stylesheet" media="all"  />
    <link type="text/css" href="https://eres.geneseo.edu/milne-styles-js/js/jquery-ui-1.10.3.custom.css" rel="stylesheet" />
    <link type="text/css" href="https://eres.geneseo.edu/milne-styles-js/js/jquery.ui.timepicker.css" rel="stylesheet" />
    <script type="text/javascript" src="https://eres.geneseo.edu/milne-styles-js/js/jquery-ui-1.10.3.custom.js"></script>
    <script type="text/javascript" src="https://eres.geneseo.edu/milne-styles-js/js/jquery.ui.timepicker.js"></script>
   <!--END INTRANET LIB CUSTOM STYLES & JQUERY LIBRARIES -->

	
<style>
@font-face {
    font-family: "Neutraface Text";
    src: url('fonts/NeutrafaceText-Book.eot');
    src: url("fonts/NeutrafaceText-Book.eot?#iefix") format("embedded-opentype"),
         url("fonts/NeutrafaceText-Book.woff2") format("woff2"),
         url("fonts/NeutrafaceText-Book.woff") format("woff");
    font-style: normal;
    font-weight: 400;
    font-stretch: normal;
}

@font-face {
    font-family: "Neutraface Headings";
    src: url('fonts/NeutrafaceText-Bold.eot');
    src: url("fonts/NeutrafaceText-Bold.eot?#iefix") format("embedded-opentype"),
         url("fonts/NeutrafaceText-Bold.woff2") format("woff2"),
         url("fonts/NeutrafaceText-Bold.woff") format("woff");
    font-style: normal;
    font-weight: 400;
    font-stretch: normal;
}

@font-face {
  font-family: 'Material Icons';
  font-style: normal;
  font-weight: 400;
  src: url(MaterialIcons-Regular.eot); /* For IE6-8 */
  src: local('../fonts/Material Icons'),
       local('fonts/MaterialIcons-Regular'),
       url(fonts/MaterialIcons-Regular.woff2) format('woff2'),
       url(fonts/MaterialIcons-Regular.woff) format('woff'),
       url(fonts/MaterialIcons-Regular.ttf) format('truetype');
}


.s-la-widget *, #s-la-widget-761
{
background:transparent !important;
background:none !important;
border:none !important;
padding-left: 5px !important;
}

.s-la-widget h1, .s-la-widget h3,  #s-la-widget-761 h1, #s-la-widget-761 h3
{
  color: #b87733 !important;
  font-weight:bold;
}

.s-la-widget .s-la-widget-header, #s-la-widget-761 .s-la-widget-header{
margin-bottom: 5px !important;
}

body, div, p, td, tr {
font-weight:normal;
}
</style>	
	


<body>
    

<div>
<div style="height: 20px;width: 100%; margin: 0px ! important;
background-color: #345290;"></div>
<div style="margin:0px 20px 20px 20px;">
    <div style="width: 100%;">   
        
<div style="float:left; margin-top:-20px;"><a href="https://www.geneseo.edu/library"><img src="https://eres.geneseo.edu/milne-logo/milne-library-logo.png" style="margin-top:0px; width:85%;"</a> </div>   	
		</div>
		
<div class="breadcrumb" style="margin-top:20px;"><a href="https://www.geneseo.edu/">SUNY Geneseo</a> &raquo; <a href="https://www.geneseo.edu/library">Milne Library</a> &raquo; <a href="https://illiad.geneseo.edu" style="color:#b85533 !important;">Information Delivery Services</a></div>
<div id="rightSideContent" >
<!--- BODY CONTENT RIGHT SIDE  BEGINS --->