</div><!-- END INTRANETLIB BODY CONTENT PLACEHOLDER -->

  </div>           
 </div>
      
 <!--/ div --> <!--mdl-grid--><!-- THIS CLOSING DIV IS IN THE GENESEO DRUPAL LAYOUT BUT NOT NEEDED HERE -->


    <div id="navigation">


      
    </div>



      </div>
  </div>



<!-- FOOTER--->
  <footer class="geneseo-footer mdl-mega-footer">
    <div class="mdl-mega-footer__middle-section geneseo-big-container">
      <div class="mdl-mega-footer__left-section">
                  <div class="mdl-logo geneseo-footer-logo">
            <a href="https://www.geneseo.edu/"><img src="https://www.geneseo.edu/sites/all/themes/geneseo/logo-full.png" alt="SUNY Geneseo"/></a>
          </div>
                <div class="geneseo-footer-copyright">
          <span>&copy; 2016 SUNY Geneseo<br></span>
          <span>1 College Circle | Geneseo, NY 14454<br></span>
          <span><a href="tel: +15852455000">(585) 245-5000</a> | <a href="mailto: web@geneseo.edu">web@geneseo.edu</a></span>
        </div>
      </div>

      <div class="mdl-mega-footer__drop-down-section">
        <h3 class="mdl-mega-footer__heading">Connect</h3>
        <ul class="mdl-mega-footer__link-list">
          <li><a href="https://www.facebook.com/SUNYGeneseo"><button class="mdl-mega-footer__social-btn mdl-shadow--3dp"><span class="socicon socicon-facebook"></span></button></a></li><li><a href="https://twitter.com/SUNYGeneseo"><button class="mdl-mega-footer__social-btn mdl-shadow--3dp"><span class="socicon socicon-twitter"></span></button></a></li><li><a href="https://www.linkedin.com/company/suny-geneseo"><button class="mdl-mega-footer__social-btn mdl-shadow--3dp"><span class="socicon socicon-linkedin"></span></button></a></li><li><a href="https://www.instagram.com/sunygeneseo/"><button class="mdl-mega-footer__social-btn mdl-shadow--3dp"><span class="socicon socicon-instagram"></span></button></a></li><li><a href="https://www.youtube.com/user/SUNYGeneseo"><button class="mdl-mega-footer__social-btn mdl-shadow--3dp"><span class="socicon socicon-youtube"></span></button></a></li>        </ul>
      </div>

      <div class="mdl-mega-footer__right-section">
        <div class="mdl-mega-footer__drop-down-section">
          <input class="mdl-mega-footer__heading-checkbox" type="checkbox" checked>
          <h3 class="mdl-mega-footer__heading">Join Us</h3><ul class="mdl-mega-footer__link-list"><li class="menu-8138 first"><a href="http://www.geneseo.edu/admissions/apply" title="">Apply to Geneseo</a></li>
<li class="menu-1956"><a href="http://www.geneseo.edu/hr/employment" title="">Work at Geneseo</a></li>
<li class="menu-1957 last"><a href="http://uknight.geneseo.edu/" title="">Alumni Community</a></li>
</ul>        </div>

        <div class="mdl-mega-footer__drop-down-section">
          <input class="mdl-mega-footer__heading-checkbox" type="checkbox" checked>
          <h3 class="mdl-mega-footer__heading">Quick Access Links</h3><ul class="mdl-mega-footer__link-list"><li class="menu-1966 first"><a href="http://www.geneseo.edu/registrar/academic-calendar" title="">Academic Calendar</a></li>
<li class="menu-1968"><a href="http://www.geneseo.edu/health" title="">Health and Counseling</a></li>
<li class="menu-1967 last"><a href="http://intranetlib.geneseo.edu/DataPortal/Requests/SupportMilneLibrary.aspx" title="">Donate to Geneseo</a></li>
</ul>        </div>

        <div class="mdl-mega-footer__drop-down-section">
          <input class="mdl-mega-footer__heading-checkbox" type="checkbox" checked>
          <h3 class="mdl-mega-footer__heading">Website Help</h3><ul class="mdl-mega-footer__link-list"><li class="menu-1971 first"><a href="https://www.geneseo.edu" title="">Site Map</a></li>
<li class="menu-1969"><a href="https://www.geneseo.edu" title="">Report a Problem</a></li>
<li class="menu-1970 last"><a href="https://www.geneseo.edu" title="">Media Information</a></li>
</ul>        </div>
      </div>
      </div>
              <div class="geneseo-footer-bottom mdl-mega-footer__bottom-section">
          <ul class="mdl-mega-footer__link-list"><li class="menu-1996 first"><a href="/" title="">Home</a></li>
<li class="menu-1998"><a href="http://www.gmail.com/" title="">Webmail</a></li>
<li class="menu-1999"><a href="https://www.geneseo.edu/emergencies" title="">Emergency Info</a></li>
<li class="menu-2002 last"><a href="https://www.geneseo.edu/cit/web-privacy-policy" title="">Privacy Policy</a></li>
<li><a href="https://www.geneseo.edu/caslogin?destination=library">Log In</a></li></ul>        </div>
        </footer>

<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-426838-5', 'auto');
  ga('send', 'pageview');

</script>
  </body>
</html>
